# Generated by Django 4.1.5 on 2023-01-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mob', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('std', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mob', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('sal', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
