# Generated by Django 4.1.5 on 2023-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
