# Generated by Django 4.1.5 on 2023-01-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='ph',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='uname',
            new_name='username',
        ),
    ]
