# Generated by Django 4.1.5 on 2023-01-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='contact_num',
        ),
    ]
