# Generated by Django 4.1.5 on 2023-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_phone_teacher_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sal',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='abcd', max_length=40),
        ),
    ]
