# Generated by Django 4.1.5 on 2023-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_teacher_sal_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='exp',
            field=models.PositiveIntegerField(default=2013),
            preserve_default=False,
        ),
    ]
