# Generated by Django 4.1.5 on 2023-01-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_teacher_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
