# Generated by Django 4.1.5 on 2023-01-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_student1_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student1',
        ),
    ]
