# Generated by Django 4.1.5 on 2023-01-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0009_delete_personaldetails_delete_school_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.PositiveBigIntegerField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=40)),
                ('school_addr', models.CharField(max_length=50)),
                ('principal', models.CharField(max_length=40)),
                ('staff_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('school_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.school')),
                ('personaldetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.personaldetails')),
                ('sid', models.CharField(max_length=20)),
                ('standard', models.PositiveIntegerField()),
                ('board', models.CharField(max_length=40)),
            ],
            bases=('app1.personaldetails', 'app1.school'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('school_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.school')),
                ('personaldetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.personaldetails')),
                ('tid', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('experience', models.PositiveIntegerField()),
                ('sal', models.PositiveIntegerField()),
            ],
            bases=('app1.personaldetails', 'app1.school'),
        ),
    ]
